#!/usr/bin/env bash
set -euo pipefail

# If --help is passed, show usage
if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  echo "=== niBuild Workflow Runner (Singularity) ==="
  echo ""
  echo "Usage:"
  echo "  Direct:    ./run_singularity.sh"
  echo "  Container: singularity run my-pipeline.sif"
  echo ""
  echo "File inputs (edit job.yml before running):"
  echo "  t1w  (File[])"
  echo "  bold  (File[])"
  echo "  mcflirt_ref_file  (File)"
  echo "  mcflirt_init  (File)"
  echo "  flirt_1_reference  (File)"
  echo "  flirt_1_init_matrix  (File)"
  echo "  flirt_1_in_weight  (File)"
  echo "  flirt_1_ref_weight  (File)"
  echo "  flirt_1_wm_seg  (File)"
  echo "  flirt_1_fieldmap  (File)"
  echo "  flirt_1_fieldmapmask  (File)"
  echo "  flirt_1_schedule  (File)"
  echo "  flirt_2_init_matrix  (File)"
  echo "  flirt_2_in_weight  (File)"
  echo "  flirt_2_ref_weight  (File)"
  echo "  flirt_2_wm_seg  (File)"
  echo "  flirt_2_fieldmap  (File)"
  echo "  flirt_2_fieldmapmask  (File)"
  echo "  flirt_2_schedule  (File)"
  echo "  fnirt_reference  (File)"
  echo "  fnirt_inwarp  (File)"
  echo "  fnirt_intin  (File)"
  echo "  fnirt_config  (File)"
  echo "  fnirt_refmask  (File)"
  echo "  fnirt_inmask  (File)"
  echo "  fslmaths_1_add_file  (File)"
  echo "  fslmaths_1_sub_file  (File)"
  echo "  fslmaths_1_mul_file  (File)"
  echo "  fslmaths_1_div_file  (File)"
  echo "  fslmaths_1_mas  (File)"
  echo "  fslmaths_1_max_file  (File)"
  echo "  fslmaths_1_min_file  (File)"
  echo "  fslmaths_2_sub_file  (File)"
  echo "  fslmaths_2_mul_file  (File)"
  echo "  fslmaths_2_div_file  (File)"
  echo "  fslmaths_2_mas  (File)"
  echo "  fslmaths_2_max_file  (File)"
  echo "  fslmaths_2_min_file  (File)"
  echo "  applywarp_reference  (File)"
  echo "  applywarp_postmat  (File)"
  echo "  applywarp_mask  (File)"
  echo ""
  echo "All scalar parameters are pre-configured in job.yml."
  echo "Edit job.yml to set file paths before running."
  echo ""
  echo "Extra arguments are passed to cwltool (e.g. --verbose, --cachedir /cache)."
  exit 0
fi

cwltool --singularity --outdir /output "$@" \
  workflows/fmri_flanker.cwl \
  job.yml
